name: build_push_to_prod_ecr

on:
  release:
    branches: [ master ]
    types: [ published ]

jobs:
  build_push_to_prod_ecr:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build image 3.1.0
        run: docker build . --tag hls-base-3.1.0 --build-arg lasrc_version=3.1.0

      - name: Push to tagged ECR 3.1.0
        id: push-tagged-ecr-310
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-west-2
          local-image: hls-base-3.1.0
          image: hls-base-3.1.0:${GITHUB_REF##*/}

      - name: Build image 3.0.5
        run: docker build . --tag hls-base-3.0.5 --build-arg lasrc_version=3.0.5

      - name: Push to tagged ECR 3.0.5
        id: push-tagged-ecr-305
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-west-2
          local-image: hls-base-3.0.5
          image: hls-base-3.0.5:${GITHUB_REF##*/}
